# Generated by Django 3.0.1 on 2020-07-29 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_orderitems_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='tex',
            field=models.IntegerField(default=0),
        ),
    ]
