# Generated by Django 3.0.1 on 2020-07-29 12:36

from django.db import migrations, models
import django.db.models.deletion
import invoice.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=30)),
                ('address', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=200)),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Sellers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=30)),
                ('address', models.CharField(default=None, max_length=100)),
                ('signature', models.ImageField(help_text='Maximum file size allowed is 2Mb', max_length=30, upload_to=invoice.models.path_and_rename_signature, validators=[invoice.models.validate_signature_image])),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('order-buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invoice.Buyers')),
                ('order-seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invoice.Sellers')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order-item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invoice.Orders')),
                ('order-items-seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invoice.Items')),
            ],
        ),
        migrations.AddField(
            model_name='items',
            name='item-seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.Sellers'),
        ),
    ]
