# Generated by Django 3.0.1 on 2020-07-29 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='item-seller',
            new_name='itemSeller',
        ),
        migrations.RenameField(
            model_name='orderitems',
            old_name='order-item',
            new_name='orderItem',
        ),
        migrations.RenameField(
            model_name='orderitems',
            old_name='order-items-seller',
            new_name='orderItemsSeller',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='order-seller',
            new_name='orderSeller',
        ),
    ]
